# Generated by Django 4.1.2 on 2022-10-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0002_category_plane_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='plane',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
