# Generated by Django 4.1.2 on 2022-10-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0003_category_slug_plane_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
